
spring:
  application:
    name: bucks
  # db
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/bucks?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，wall用于防火墙
      filters: stat
      # 慢SQL日志
      filter:
        stat:
        enabled: true
        log-slow-sql: true
        slow-sql-millis: 1
      initial-size: 10
      log-abandoned: true
      max-active: 30
      max-open-prepared-statements: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 30000
      min-idle: 10
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      test-on-borrow: false
      tst-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      # 验证数据库连接的查询语句
      validation-query: SELECT 1

  # mongodb
  data:
    mongodb:
      uri: mongodb://localhost/kunbu
      port: 27017
      username:
      password:
  # redis
  redis:
    host: localhost
    # Redis服务器连接端口
    port: 6379
    password:
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最小空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000ms
    # 连接超时时间（毫秒）
    timeout: 5000ms
    #默认是索引为0的数据库
    database: 0



# mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml

# log4j2
logging:
  config: classpath:log4j2.yml

# port
server:
  port: 9090

